### ISSUE TITLE
Navigating issue

### ISSUE THREAD

**Issue by mathangn** [fssa-batch3/parameshwari.arumugam__web_project#10]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMzY2ZmI5NWItYjY5Mi00NTNjLWEwM2MtMWMyZmVhNjk5ODgyIiwiZGVwbG95X2lkIjoiNjQ0ODEzNjJkNjBiMDYwMDA4ZmI2NDg5IiwiaWQiOiI0YjhiZGM1ZS02MzlmLTQ1ZWMtOTIwYS04NDBhOWRjZjMwMTcifQ==)

### Description of issue
On the registration page, if a user fills in the details, the user navigated to the home page

### Expected result
The user navigates to the login page.

### Actual result
It's navigated to the home page. but in the readme file, she wrote if a user signup the details it navigates to the login page. 

### Steps to reproduce
1. Go to the signup page.
2. Fill your details and click the signup button.
3. It navigates to the home page.

```
Path:      /
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--flowery-bouquet.netlify.app%2F&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--flowery-bouquet.netlify.app/)

**Comment by Parameshwari2004** [comment]
I am finished this bug . Please check this again

**Comment by mathangn** [comment]
Okay, I have checked this bug. This bug cleared. So I closed this bug.
