### ISSUE TITLE
Cart quantity isn't visible

### ISSUE THREAD

**Issue by mathangn** [fssa-batch3/parameshwari.arumugam__web_project#11]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMzY2ZmI5NWItYjY5Mi00NTNjLWEwM2MtMWMyZmVhNjk5ODgyIiwiZGVwbG95X2lkIjoiNjQ1OGMxMDVhZTNkNzcwMDA4ZjVhNjYzIiwiaWQiOiI5ZGExYWMwMy03MGE2LTRkYjItODNhNS05Y2M5OTQ2NzJiYzUifQ==)

### Description of issue
In the Anniversary bouquet page cart count is not visible.

### Expected result
In the Anniversary bouquet page cart count is visible.

### Actual result
It will be the cart product count

### Steps to reproduce
1. go to the anniversary bouquet page
2. on the cart icon cart count is not visible
3. 

```
Path:      /pages/anniversary/anni-bouquet
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--flowery-bouquet.netlify.app%2Fpages%2Fanniversary%2Fanni-bouquet&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--flowery-bouquet.netlify.app/pages/anniversary/anni-bouquet)

**Comment by Parameshwari2004** [comment]
I am  finished this bug . Please check this again.

**Comment by Parameshwari2004** [comment]
I am finished this bug . Please check this again
