### ISSUE TITLE
Time issue

### ISSUE THREAD

**Issue by mathangn** [fssa-batch3/parameshwari.arumugam__web_project#13]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMzY2ZmI5NWItYjY5Mi00NTNjLWEwM2MtMWMyZmVhNjk5ODgyIiwiZGVwbG95X2lkIjoiNjQ2MTA3YWM3YTEyYTUwMDA4ZmNlZDQzIiwiaWQiOiIxODY2N2VlMi1lMjQ4LTRlNDYtYmMyMS1iMGM1ZWI5ZDZjNWQifQ==)

### Description of issue
The input box accepts the past time.

### Expected result
The will not accepts the past time.

### Actual result
The input box accepts the past time.

### Steps to reproduce
1. In the payment page the delivery date input box put today date
2. And the delivery time input box put the past time 
3. And then click the place order it will accepting the order.

```
Path:      /pages/order/buy%20now?id=2
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--flowery-bouquet.netlify.app%2Fpages%2Forder%2Fbuy%2520now%3Fid%3D2&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--flowery-bouquet.netlify.app/pages/order/buy%20now?id=2)

**Comment by Parameshwari2004** [comment]
I am finished this bug . Please check this again

**Comment by mathangn** [comment]
Cleared
