### ISSUE TITLE
Order Tracker Page Product Quantity

### ISSUE THREAD

**Issue by mathangn** [fssa-batch3/parameshwari.arumugam__web_project#16]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMzY2ZmI5NWItYjY5Mi00NTNjLWEwM2MtMWMyZmVhNjk5ODgyIiwiZGVwbG95X2lkIjoiNjQ2YjY3YzNiMDMyYzEwMDA4MWNiYzIzIiwiaWQiOiIwOGQ3YWUxYi0yNWIwLTQ1ZTgtOTljNS0wM2NjOTM0MjcyZGEifQ==)

### Description of issue
Order tracker page product price is wrong.

### Expected result
Order tracker page product price should correct and also add product quantity.

### Actual result
Order tracker page product price is wrong.

### Steps to reproduce
1. if i order two product via the cart.
2. And i ordered more then one product if the product price also increased. but the order tracker page is not visible the quantity of product and also one  product only ordered the tracker page.

```
Path:      /pages/order/orderhistory
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--flowery-bouquet.netlify.app%2Fpages%2Forder%2Forderhistory&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--flowery-bouquet.netlify.app/pages/order/orderhistory)

**Comment by Parameshwari2004** [comment]
I am finished this bug . Please check this again

**Comment by mathangn** [comment]
Cleared
