### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by mathangn** [fssa-batch3/parameshwari.arumugam__web_project#17]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMzY2ZmI5NWItYjY5Mi00NTNjLWEwM2MtMWMyZmVhNjk5ODgyIiwiZGVwbG95X2lkIjoiNjQ2YjY3YzNiMDMyYzEwMDA4MWNiYzIzIiwiaWQiOiI3MjM3ZTAyOC1hZWVmLTQwMDctYjNiZS1iYjgzYjlhMWZhMzQifQ==)

### Description of issue
In the index page Sign up Tittle as mistaked.

### Expected result
Tittle Should be change"Sing up" to "Sign up"

### Actual result
In the index page Sign up Tittle as mistaked.

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /index.html
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--flowery-bouquet.netlify.app%2Findex.html&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--flowery-bouquet.netlify.app/index.html)

**Comment by Parameshwari2004** [comment]
I am finished this bug . Please check this again

**Comment by mathangn** [comment]
Cleared
