### ISSUE TITLE
Order History Page Cancel button isn't Working

### ISSUE THREAD

**Issue by mathangn** [fssa-batch3/parameshwari.arumugam__web_project#19]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMzY2ZmI5NWItYjY5Mi00NTNjLWEwM2MtMWMyZmVhNjk5ODgyIiwiZGVwbG95X2lkIjoiNjQ2YjY3YzNiMDMyYzEwMDA4MWNiYzIzIiwiaWQiOiIyYTIwNGJlNS05NzIwLTQ2NDYtODczNy03NDY4ZDUwMGEwNzgifQ==)

### Description of issue
If i cancelled one order that order is cancelled. but i cancelled more then one order isn't working. 

### Expected result
if the user click the cancel button the order will be cancelled.

### Actual result
If i cancelled one order that order is cancelled. but i cancelled more then one order isn't working. 

### Steps to reproduce
1. On the order history page if i clicked the cancel button that order will be cancelled.
2. but i click the cancel button more then one order first order only cancelled.  
3.  

```
Path:      /pages/order/orderhistory
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--flowery-bouquet.netlify.app%2Fpages%2Forder%2Forderhistory&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--flowery-bouquet.netlify.app/pages/order/orderhistory)

**Comment by Parameshwari2004** [comment]
I am finished this bug . Please check this again

**Comment by mathangn** [comment]
Cleared
