### ISSUE TITLE
Order Total price is not correct

### ISSUE THREAD

**Issue by mathangn** [fssa-batch3/parameshwari.arumugam__web_project#20]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMzY2ZmI5NWItYjY5Mi00NTNjLWEwM2MtMWMyZmVhNjk5ODgyIiwiZGVwbG95X2lkIjoiNjQ2YjY3YzNiMDMyYzEwMDA4MWNiYzIzIiwiaWQiOiI2Yzk0NWM4OS1kZTBjLTQyYWItYTZlNS0yMTA4MmJmODFiNmIifQ==)

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMzY2ZmI5NWItYjY5Mi00NTNjLWEwM2MtMWMyZmVhNjk5ODgyIiwiZGVwbG95X2lkIjoiNjQ2YjY3YzNiMDMyYzEwMDA4MWNiYzIzIiwiaWQiOiIxMmI3MDRjMi00ODcyLTQ4OWEtYWM1OC1mMGZjOTFhYTAyMmUifQ==)

### Description of issue
If i ordered one prodcut that total price is correct. but i increased that product quantity that total price is wrong.

### Expected result
if you can mention that product price and how many quantity some product the user want. 

### Actual result
If i ordered one prodcut that total price is correct. but i increased that product quantity that total price is wrong.

### Steps to reproduce
1. If i ordered one product two quantity. In the order history page that product price only it's showing.
2.  And also Show the product of quantity.
3.  Should multiple the product price and quantity.

```
Path:      /pages/order/orderhistory
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--flowery-bouquet.netlify.app%2Fpages%2Forder%2Forderhistory&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--flowery-bouquet.netlify.app/pages/order/orderhistory)

**Comment by Parameshwari2004** [comment]
I am finished this bug . Please check this again

**Comment by mathangn** [comment]
Cleared
