### ISSUE TITLE
Not linked profile page

### ISSUE THREAD

**Issue by mathangn** [fssa-batch3/parameshwari.arumugam__web_project#21]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMzY2ZmI5NWItYjY5Mi00NTNjLWEwM2MtMWMyZmVhNjk5ODgyIiwiZGVwbG95X2lkIjoiNjQ2YjY3YzNiMDMyYzEwMDA4MWNiYzIzIiwiaWQiOiI2ZTRhNjQ0OS0xODYzLTQwZTktODFiOC02NTYzMzVjN2ZjZDEifQ==)

### Description of issue
On the review page if i clicked profile icon it don't navigation to the Profile page.

### Expected result
It should Navigate to the Profile page

### Actual result
On the review page if i clicked profile icon it don't navigation to the Profile page.

### Steps to reproduce
1. On the review page if i click the Profile icon i don't navigate to the profile page.
2. 
3. 

```
Path:      /pages/review
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--flowery-bouquet.netlify.app%2Fpages%2Freview&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--flowery-bouquet.netlify.app/pages/review)

**Comment by Parameshwari2004** [comment]
I am finished this bug . Please check this again

**Comment by mathangn** [comment]
Cleared
