### ISSUE TITLE
Email pattern isn't working

### ISSUE THREAD

**Issue by mathangn** [fssa-batch3/parameshwari.arumugam__web_project#3]
### Description of issue
Email pattern isn't working

### Expected result
Email required @gmail.com and other type of mails end code also required.
e.g: @gmail.com, @outlook.com.

### Actual result
Email pattern isn't working and @gmail.com is required.

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--flowery-bouquet.netlify.app%2F&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--flowery-bouquet.netlify.app/)

**Comment by Parameshwari2004** [comment]
Email pattern issue is cleared
