### ISSUE TITLE
Password pattern and min, max limit

### ISSUE THREAD

**Issue by mathangn** [fssa-batch3/parameshwari.arumugam__web_project#5]
[example](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMzY2ZmI5NWItYjY5Mi00NTNjLWEwM2MtMWMyZmVhNjk5ODgyIiwiZGVwbG95X2lkIjoiNjQzN2NjNWVmYzMxMjkwMDA4YTE5ZDI0IiwiaWQiOiI4YzVhYzUxYy00MTZiLTQ3OGQtYTQ3Zi04MGM4M2Y0Y2Y5YjkifQ==)
### Description of issue
Password pattern is not working and passwork did have min max limit.

### Expected result
Special Characters is must required and numbers also required

### Actual result
Password pattern is not working 

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--flowery-bouquet.netlify.app%2F&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--flowery-bouquet.netlify.app/)

**Comment by Parameshwari2004** [comment]
I am finished this bug . Please check this again

**Comment by mathangn** [comment]
Okay, I have checked this bug. This bug cleared. So I closed this bug.
