### ISSUE TITLE
Password Pattern In the Login Page

### ISSUE THREAD

**Issue by mathangn** [fssa-batch3/parameshwari.arumugam__web_project#6]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMzY2ZmI5NWItYjY5Mi00NTNjLWEwM2MtMWMyZmVhNjk5ODgyIiwiZGVwbG95X2lkIjoiNjQzN2NjNWVmYzMxMjkwMDA4YTE5ZDI0IiwiaWQiOiI5NDI3YzQ3Yi1kNTczLTQzY2MtYjExMS0yM2M1MzUwYzQzOTgifQ==)

### Description of issue
Password is working but pattern limit is worng.
In the login page password input box only accepting  1 to 6 characters.

### Expected result
Set the minimum limit 8 characters

### Actual result
Accept minimum 8  characters limit to max 16 or 24.

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /pages/login.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--flowery-bouquet.netlify.app%2Fpages%2Flogin.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--flowery-bouquet.netlify.app/pages/login.html)

**Comment by Parameshwari2004** [comment]
I am finished this bug . Please check this again

**Comment by mathangn** [comment]
Okay, I have checked this bug. This bug cleared. So I closed this bug.
