### ISSUE TITLE
Profile page details is not matched the active user

### ISSUE THREAD

**Issue by mathangn** [fssa-batch3/parameshwari.arumugam__web_project#7]
https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMzY2ZmI5NWItYjY5Mi00NTNjLWEwM2MtMWMyZmVhNjk5ODgyIiwiZGVwbG95X2lkIjoiNjQzN2NjNWVmYzMxMjkwMDA4YTE5ZDI0IiwiaWQiOiIxNGEzYTYyMy04MGI2LTQ3ZjAtOGNhZC00ZDg0NmFiYmEwZDMifQ==

### Description of issue
Profile page details is not matched the active user it's slowed the last user details

### Expected result
which user logged in that user details solw in the profile page.

### Actual result
Profile page details is not matched the active user it's slowed the last user details

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /pages/profile.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--flowery-bouquet.netlify.app%2Fpages%2Fprofile.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--flowery-bouquet.netlify.app/pages/profile.html)

**Comment by Parameshwari2004** [comment]
I am finished this bug . Please check this again

**Comment by mathangn** [comment]
Okay, I have checked this bug. This bug cleared. So I closed this bug.
